server:
  port: 80
  tomcat:
    max-http-form-post-size: 8192
  max-http-header-size: 8192
spring:
  mail: #开启POP3之后设置的客户端授权码
    host: smtp.qq.com
    username: xxx  #用自己的
    password: xxx #用自己的
    default-encoding: UTF-8
    properties.mail.smtp.ssl.enable: true
    port: 465
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_yunpin?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #关键部分。用来显示sql
alioss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: xxx #用自己的
  accessKeySecret: xxx #用自己的
  roleArn: xxx:role/study #用自己的
  regionID: cn-hangzhou
  bucket: xxx #用自己的
